export const CODING_SCENARIOS = [
  {
    id: "coding-debug",
    name: "复杂问题：代码排错",
    category: "coding",
    difficulty: "complex",
    prompt: [
      "你是一名负责高并发 API 网关的资深后端工程师。下面这段 Node.js 代码在生产环境偶发请求超时，请定位根因并给出可直接上线的修复方案。",
      "",
      "```js",
      "async function callUpstream(url, payload) {",
      "  const controller = new AbortController();",
      "  setTimeout(() => controller.abort(), 30000);",
      "  const response = await fetch(url, {",
      "    method: 'POST',",
      "    body: JSON.stringify(payload),",
      "    signal: controller.signal",
      "  });",
      "  return response.json();",
      "}",
      "```",
      "",
      "要求：分成「问题原因、修复代码、上线风险」三部分；问题原因要指出具体是哪个机制（如超时与 AbortController / clearTimeout 的关系）导致；修复代码给出可整段替换的完整函数。回答尽可能简短。",
    ].join("\n"),
    minChars: 100,
    requiredAny: ["问题原因", "修复", "风险", "AbortController", "clearTimeout"],
  },
];
