export const CODING_SCENARIOS = [
  {
    id: "coding-debug",
    name: "复杂问题：代码排错",
    category: "coding",
    difficulty: "complex",
    prompt: [
      "你是一名负责高并发 API 网关的资深后端工程师。下面这段 Node.js 代码在生产环境偶发请求超时，请定位根因并给出可直接上线的修复方案。",
      "",
      "```js",
      "async function callUpstream(url, payload) {",
      "  const controller = new AbortController();",
      "  setTimeout(() => controller.abort(), 30000);",
      "  const response = await fetch(url, {",
      "    method: 'POST',",
      "    body: JSON.stringify(payload),",
      "    signal: controller.signal",
      "  });",
      "  return response.json();",
      "}",
      "```",
      "",
      "要求：分成「问题原因、修复代码、上线风险」三部分；问题原因要指出具体是哪个机制（如超时与 AbortController / clearTimeout 的关系）导致；修复代码给出可整段替换的完整函数。回答尽可能简短。",
    ].join("\n"),
    minChars: 100,
    requiredAny: ["问题原因", "修复", "风险", "AbortController", "clearTimeout"],
  },
  {
    id: "coding-reverse-string",
    name: "代码：字符串反转",
    category: "coding",
    difficulty: "small",
    prompt: "请用 JavaScript 写一个函数 reverseString(s)，接收一个字符串，返回字符顺序反转后的字符串。只需给出函数代码，可附一句说明。例如 reverseString('abc') 应返回 'cba'。",
    minChars: 30,
    requiredAny: ["function", "reverseString", "reverse", "split", "=>"],
  },
  {
    id: "coding-dedup-array",
    name: "代码：数组去重",
    category: "coding",
    difficulty: "small",
    prompt: "用 JavaScript 写一个函数 unique(arr)，返回去掉重复元素后的新数组，并保持元素首次出现的顺序。给出函数代码并简述实现思路。例如 unique([1,2,2,3,1]) 应返回 [1,2,3]。",
    minChars: 40,
    requiredAny: ["Set", "unique", "function", "filter", "indexOf", "=>"],
  },
  {
    id: "coding-is-prime",
    name: "代码：判断质数",
    category: "coding",
    difficulty: "small",
    prompt: "写一个函数 isPrime(n) 判断正整数 n 是否为质数，返回布尔值。语言不限，给出完整函数，并说明对边界情况（如 n < 2）的处理。",
    minChars: 50,
    requiredAny: ["质数", "prime", "return", "function", "def", "sqrt"],
  },
  {
    id: "coding-sql-topn",
    name: "代码：SQL 查询 Top-N",
    category: "coding",
    difficulty: "normal",
    prompt: "给定一张订单表 orders(user_id, amount)，写一条 SQL：统计每个用户的订单总金额，并按总金额从高到低取前 5 名。给出 SQL 语句并简要说明。",
    minChars: 50,
    requiredAny: ["SELECT", "GROUP BY", "SUM", "ORDER BY", "LIMIT", "DESC"],
  },
  {
    id: "coding-fetch-retry",
    name: "代码：带重试的上游请求",
    category: "coding",
    difficulty: "normal",
    prompt: "你在维护一个调用上游 API 的网关。请用 JavaScript 写一个 fetchWithRetry(url, options, retries) 函数：请求失败时最多重试 retries 次，每次重试前按指数退避等待。给出完整函数，并说明退避策略。",
    minChars: 80,
    requiredAny: ["retry", "重试", "退避", "backoff", "fetch", "async", "await"],
  },
  {
    id: "coding-safe-json-parse",
    name: "代码：安全解析 JSON",
    category: "coding",
    difficulty: "normal",
    prompt: "网关经常要解析上游返回的 JSON，偶尔会收到非法 JSON 导致抛错。请写一个 safeParse(text, fallback) 函数：能正常解析就返回对象，解析失败返回 fallback，绝不抛出异常。给出函数代码并说明为何要这样处理。",
    minChars: 60,
    requiredAny: ["try", "catch", "JSON.parse", "fallback", "异常", "return"],
  },
  {
    id: "coding-explain-async",
    name: "代码：解释 async/await",
    category: "coding",
    difficulty: "normal",
    prompt: "请用通俗的语言向初级工程师解释 JavaScript 中 async/await 的作用，以及它与直接使用 Promise.then 相比的好处。要求结合一个简单代码示例，说明为什么 await 能让异步代码写得像同步一样。",
    minChars: 100,
    requiredAny: ["async", "await", "Promise", "异步", "同步", "then"],
  },
];
